using Microsoft.AspNetCore.SpaServices.ReactDevelopmentServer;
using Microsoft.Extensions.FileProviders;

namespace RaiNbow.API.Configuration;

internal static class Frontend
{
    internal static IApplicationBuilder UseFrontend(this WebApplication app)
    {
        if (app.Configuration.GetValue<bool>("HostUI"))
        {
            app.UseSpa(spa =>
            {
                var clientAppPath = Path.Combine(Directory.GetCurrentDirectory(), "..", "..", "ui");
                spa.Options.SourcePath = clientAppPath;
                if (app.Environment.IsDevelopment())
                {
                    spa.UseReactDevelopmentServer(npmScript: "start");
                }
                else
                {
                    // If not in development, serve the static files generated by 'npm run build'
                    spa.Options.DefaultPageStaticFileOptions = new StaticFileOptions
                    {
                        FileProvider = new PhysicalFileProvider(
                            Path.Combine(app.Environment.ContentRootPath,
                                clientAppPath,
                                "build"))
                    };
                }
            });
        }

        return app;
    }
}